#! /usr/bin/env bash

readonly DIR=$(dirname $0)
readonly CWD=$(pwd)

#echo CWD=${CWD}
#echo ${DIR}

#function getSoPath() {
#    local CP=$(mvn -file ${DIR} dependency:build-classpath | grep -v "^\[")
#    local P
#    for P in $(echo ${CP} | tr ":" " "); do
#        if echo $P | grep spencer-tracing-jni; then
#            P=$(echo ${P} | sed "s/\.pom/\.so/")
#            echo "$P"
#            return
#        fi
#    done
#}

#AGENT=$(getSoPath | grep -v pom)

#echo -e "AGENT is ${AGENT}"
MAIN="-Dexec.mainClass=\"com.github.kaeluka.spencer.Main\""
CMD="mvn --file ${DIR}/pom.xml exec:java ${MAIN} -Dexec.arguments=\"$@\""
echo "${CMD}"
/bin/bash -c "${CMD}"
